apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mft-pvc
  labels:
    app: mft
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: "ocs-storagecluster-cephfs"  
